[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.8.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações para ignorar avisos de importação
[build.processing.js]
  bundle = true
  minify = true

# Configurações para ignorar erros específicos
[context.production.environment]
  NEXT_IGNORE_ESLINT = "true"
  NEXT_IGNORE_TYPE_CHECK = "true"
