const { extrairDadosTexto } = require('../src/lib/ocr/ocr-processor');

// Let's test the current extract
const textoASO = `Médico Responsável pela PCMSO Dr Heloana Antunes Sabino da Azevado NE A CRM-RJ: 52 80456-4 1 RQE: 27590 FER Re Sn Av. Nossa Senhora da Glória, nº 2067 - 304 mm Em fika Gavaloiros - Macaé! RJ Telefone: 122) 8717-1170 I Ú ATESTADO DE SAUDE OCUPACIONAL 622769 ' NOME; CAIO VALERIO GOULART CORREIA a, [AGUAS BRASILEIRAS SERVICOS E CONSULTORIA EM ATIVIDADES ! I " EMPRESA: ; é IDS/00081.85 MARITIMAS LTDA SNPJ: 17.784 3OS/0001-8 FUNÇÃO. - ANALISTADE SUPORTE ! SETOR: AÉZ BASE i , CPF: 154 15687764 ' RG/ORGÃO: 28.356,467-2 DIC D.h: 11/12/1885 [Em cumprimento aos 1º$ e 3ºÉ do Artigo 156 da Lei nº 8,514, Portaria 1214/78, Portaria 3.464/82, Portaria 12/9234/94 5 8/96 da NR-? e os jts 0.1.1, 50.21, 303.14, 90,9.2.1 e os Quadros II da NR-30 do Ministério do Trabalho, para fins de exame: Admissional . " RISCOS OCUPACIONAIS: e ERGONÔMICO Postura Inadequada, Arranjo Físico, Mavimentos Regetitivos de Mãos e Dados I ACIDENTE I Queda de Pessoa com Diferença de Nivel Preenchimento e responsabifidade exelusiva de DM baseado no PCMSO vigente: FA AA ME [I (íaeo - I gARoAFOATE [TRAGO EN ESPAÇO BERRO O a art -- I wo PocAvE [PARA TRABALHAR COM ELETRETTAÇE O OO io I Ro APOCAVEL [FARS TRANSFERÊNCIA POR CESTO OO TI Po Bo É IADAPLICÁVEL Eis E RE RE EEE O GH A ABI I RPRAG APGAVEL EG DE RESGATE EN ESPAÇO CONFIO O Ig isto [o NRO APOEATEC [PARA TRABALHAR EM REGIME BFEERGRE O Ego BIo I fe noRPOCAVED I PROCEDIMENTOS . BATA PROCEDIMENTOS DATA ACUIDADE 4 SUAL 17/03/2028 RAIO X COLUNA LOMBAR ' 1703/2025 E ETROCARDIOGR AMA 17/03/2095 TIPOE FATOR RI cz do sad do T7:03/2025 EXAME CLINICO - ASO 17/03/2025 Gi COSE 17/03/2025 HEMOGRANA COMPLETO ioNZORS = I -- = => E A e I Médico Examinador kh, Corolimo Gi Asa lt Lil Belegato 126 mMrnanta MucancE, MÉDICA ( 7 E to Food. BITICI-NodAS, sro Em 2 38 ccesters! 17 CA = Hosecel vila 2cão " TEA 52.011 5827-4 . NES oa a Boa Wistaiso Serra E 5 - o Fa Evariso 23 Wega EE 776 qTdaro Dentes = Ride ianosocRO Assinatura I Carimbo Médico Examinador DEI ag T tio S irénio ds Médics Reponvive pelo PEV ÉS, I Convluzaonigf APTO(s) [ VINAPTOIA) Asa Bona emenda AAA T Dea Conclusão AGO De cd ES 16 MAR 205 ;`;

console.log('Current extractor output:');
try {
  console.log(extrairDadosTexto(textoASO, 'aso'));
} catch (e) {
  console.error(e);
}
